spring:
  application:
    name: zipkin-server
  datasource:
    url: ${ZIPKIN_MYSQL_URL:jdbc:mysql://localhost:33066/zipkin}
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

armeria:
  ports:
    - port: 9411
      protocols:
        - HTTP

zipkin:
  storage:
    type: mysql
  self-tracing.enabled: true

server:
  port: 9412
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
